FROM python:3.13-slim

WORKDIR /app

RUN pip install uv

COPY ../pyproject.toml ../uv.lock ./

RUN uv sync --frozen --no-dev --no-install-project

COPY ./src ./

RUN rm -rf pyproject.toml uv.lock Dockerfile

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]